
export const GET_USER_IN_USERS = 'GET_USER_IN_USERS';
export const GET_CONVERSATIONS_IN_USERS = 'GET_CONVERSATIONS_IN_USERS';


export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const CHECK_TOKEN_VALIDITY_REQUEST = 'CHECK_TOKEN_VALIDITY_REQUEST';
export const CHECK_TOKEN_VALIDITY_SUCCESS = 'CHECK_TOKEN_VALIDITY_SUCCESS';
export const CHECK_TOKEN_VALIDITY_FAILURE = 'CHECK_TOKEN_VALIDITY_FAILURE';

export const SET_CONVERSATIONS_SUCCESS = 'SET_CONVERSATIONS_SUCCESS';
export const SET_CONVERSATIONS_REQUEST = 'SET_CONVERSATIONS_REQUEST';
export const SET_CONVERSATIONS_FAILURE = 'SET_CONVERSATIONS_FAILURE';
export const ADD_A_CONVERSATION = 'ADD_A_CONVERSATION';

export const ADD_USER = 'ADD_USER';

export const SET_USERS = 'SET_USERS';
export const SET_USERS_REQUEST = 'SET_USERS_REQUEST';
export const SET_USERS_SUCCESS = 'SET_USERS_SUCCESS';
export const SET_USERS_FAILURE = 'SET_USERS_FAILURE';
export const USER_CONNECTED = 'USER_CONNECTED';
export const USER_DISCONNECTED = 'USER_DISCONNECTED';

export const SET_SOCKET = 'SET_SOCKET';
export const SET_SOCKET_REQUEST = 'SET_SOCKET_REQUEST';
export const SET_SOCKET_SUCCESS = 'SET_SOCKET_SUCCESS';
export const SET_SOCKET_FAILURE = 'SET_SOCKET_FAILURE';

export const GOT_NEW_MESSAGE = 'GOT_NEW_MESSAGE';
export const SENT_NEW_MESSAGE = 'SEND_NEW_MESSAGE';
export const HANDLE_GOT_NEW_MESSAGE = 'HANDLE_GOT_NEW_MESSAGE';

export const ADD_A_NEW_MESSAGE_REQUEST = 'ADD_A_NEW_MESSAGE_REQUEST';
export const ADD_A_NEW_MESSAGE_SUCCESS = 'ADD_A_NEW_MESSAGE_SUCCESS';
export const ADD_A_NEW_MESSAGE_FAILURE = 'ADD_A_NEW_MESSAGE_FAILURE';


export const SET_ALL_MESSAGES_FOR_THIS_USER_REQUEST = 'SET_ALL_MESSAGES_FOR_THIS_USER_REQUEST';
export const SET_ALL_MESSAGES_FOR_THIS_USER_SUCCESS = 'SET_ALL_MESSAGES_FOR_THIS_USER_SUCCESS';
export const SET_ALL_MESSAGES_FOR_THIS_USER_FAILURE = 'SET_ALL_MESSAGES_FOR_THIS_USER_FAILURE';

export const SET_MESSAGES_FOR_A_CONVERSATION_REQUEST = 'SET_MESSAGES_FOR_A_CONVERSATION_REQUEST';
export const SET_MESSAGES_FOR_A_CONVERSATION_SUCCESS = 'SET_MESSAGES_FOR_A_CONVERSATION_SUCCESS';
export const SET_MESSAGES_FOR_A_CONVERSATION_FAILURE = 'SET_MESSAGES_FOR_A_CONVERSATION_FAILURE';